[package]
name = "temp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
reth.workspace = true
reth-exex.workspace = true

[lints]
workspace = true
